### ISSUE TITLE
Old postgresql client has trouble with new DBD::Pg versions due to bug in old postgresql client libraries

### ISSUE THREAD

**Issue by singingfish** [bucardo/dbdpg#109]
Demonstrate the problem via psql on Centos5 (yuk, I know ... ) using postgresql and postgresql-devel packages version 8.1.23:

```
$ psql -U myname -h mypg.host.name  nxpdb
Password for user myname 
Welcome to psql 8.1.23 (server 15beta4 (Debian 15~beta4-1.pgdg110+1)), the PostgreSQL interactive terminal.
...

WARNING:  You are connected to a server with major version 0.0,
but your psql client is major version 8.1.  Some backslash commands,
such as \d, might not work properly.

nxpdb=> \q
```

Then with `DBI->connect` we get the  below:

```
$ perl -MDBI -e 'print DBI->connect("dbi:Pg:dbname=nxpdb;host=nxpgit02.internal.nxp.co.nz", "nxnz", "nxnz") . "\n"'
DBI connect('dbname=nxpdb;host=nxpgit02.internal.nxp.co.nz','nxnz',...) failed: Server version 8.0 required at -e line 1
```

This patch works, but is probably suboptimal:

```
diff --git a/dbdimp.c b/dbdimp.c
index 72158d2..98effab 100644
--- a/dbdimp.c
+++ b/dbdimp.c
@@ -214,7 +214,8 @@ int dbd_db_login6 (SV * dbh, imp_dbh_t * imp_dbh, char * dbname, char * uid, cha
            something it should never do. If we think this is the case for the version failure, we 
            simply allow things to continue with a faked version. See github issue #47
         */
-        if (NULL != strstr(PQparameterStatus(imp_dbh->conn, "server_version"), "bouncer")) {
+        /* Also workaround a bug with ancient pg clients not knowing versions >= 10.0 */
+        if (imp_dbh->pg_server_version == 0 || NULL != strstr(PQparameterStatus(imp_dbh->conn, "server_version"), "bouncer")) {
            imp_dbh->pg_server_version = 90600;
         }
         else {
```

**Comment by jonjensen** [comment]
@singingfish I'm not one of the official maintainers here, but I believe the DBD::Pg project doesn't intend to add any new support of versions of Postgres that are long, long beyond their end of life.

If you've got this fixed in your own build of DBD::Pg and it solves your immediate problem, that seems like a win all by itself! But unless I'm missing something, it doesn't seem important for mainline DBD::Pg to have.

**Comment by singingfish** [comment]
Not sure.  Maybe worth a note in the docs - there are still old centos5
installs around, or maybe there are tests that can be done to determine the
version in that instance that are more robust than looking for version 0 to
detect ancient postgresql libraries.

**Comment by singingfish** [comment]
In general if one were to encounter this, route it through a pgbouncer on a more modern system.  Note that with ancient SSL and hashing on old systems like centos5, you'll have to use md5 passwords and terminate ssl at the pgbouncer
