### ISSUE TITLE
Error building DBD::Pg on macOS Monterey

### ISSUE THREAD

**Issue by carragom** [bucardo/dbdpg#110]
Hi,

First I'm sorry for copying/pasting this issue as it's almost the same as the one I just reported in DBD-SQLite/DBD-SQLite#106

I had some trouble installing this module on macOS Monterey (12.6.3) using the OS `/usr/bin/perl` interpreter (v5.30.3)

```
$ perl Makefile.PL
Configuring DBD::Pg 3.16.0
PostgreSQL version: 140006 (default port: 5432)
POSTGRES_HOME: (not set)
POSTGRES_INCLUDE: /usr/local/include/postgresql@14
POSTGRES_LIB: /usr/local/lib/postgresql@14
OS: darwin
Checking if your kit is complete...
Looks good
Warning (mostly harmless): No library found for -lm
Using DBI 1.643 (for perl 5.030003 on darwin-thread-multi-2level) installed in /System/Library/Perl/Extras/5.30/darwin-thread-multi-2level/auto/DBI/
Generating a Unix-style Makefile
Writing Makefile for DBD::Pg
Writing MYMETA.yml and MYMETA.json
$ make
cp lib/Bundle/DBD/Pg.pm blib/lib/Bundle/DBD/Pg.pm
cp Pg.pm blib/lib/DBD/Pg.pm
Running Mkbootstrap for Pg ()
chmod 644 "Pg.bs"
"/usr/bin/perl" -MExtUtils::Command::MM -e 'cp_nonempty' -- Pg.bs blib/arch/auto/DBD/Pg/Pg.bs 644
make: *** No rule to make target `/System/Library/Perl/Extras/5.30/darwin-thread-multi-2level/auto/DBI/Driver_xst.h', needed by `Pg.xsi'.  Stop.
```

In order to make it work I had to modify the final `Makefile` as following:

```diff
--- Makefile.old        2023-02-06 19:24:06.000000000 -0600
+++ Makefile    2023-02-06 19:24:10.000000000 -0600
@@ -161,7 +161,7 @@
 PARENT_NAME = DBD
 DLBASE = $(BASEEXT)
 VERSION_FROM = Pg.pm
-INC = -I/usr/local/include/postgresql@14 -I/System/Library/Perl/Extras/5.30/darwin-thread-multi-2level/auto/DBI
+INC = -I/usr/local/include/postgresql@14 -I$(SDKROOT)$(DBI_INSTARCH_DIR)
 OBJECT = Pg$(OBJ_EXT) dbdimp$(OBJ_EXT) quote$(OBJ_EXT) types$(OBJ_EXT)
 LDFROM = $(OBJECT)
 LINKTYPE = dynamic
@@ -972,7 +972,7 @@
 # This dependency is needed since MakeMaker uses the .xs.o rule
 $(BASEEXT)$(OBJ_EXT): $(BASEEXT).xsi

-$(BASEEXT).xsi: $(DBI_DRIVER_XST) /System/Library/Perl/Extras/5.30/darwin-thread-multi-2level/auto/DBI/Driver_xst.h
+$(BASEEXT).xsi: $(DBI_DRIVER_XST)
        $(PERL) -p -e "s/~DRIVER~/$(BASEEXT)/g; s/^do\(/dontdo\(/" $(DBI_DRIVER_XST) > $(BASEEXT).xsi

 # ---
```

- The first change fixes the include path to point to where the `DBIXS.h` and other header files are located.
- The second change removes a reference to a non-existent file `Driver_xst.h` which does not seem to be needed at all. But can also be replace with `$(SDKROOT)$(DBI_INSTARCH_DIR)/Driver_xst.h` for the correct file path if wanted. Either way it compiles correctly.

Sadly I can't provide a patch to fix how the final `Makefile` is generated but hopefully this could be a starting point to a complete fix.

**Comment by esabol** [comment]
Nitpick: Monterey has been misspelled in the issue title. @carragom: Please fix in order to make the issue search engine optimized. :smile:

**Comment by carragom** [comment]
Sorry about that, title fixed.

**Comment by turnstep** [comment]
I think this might be a DBI issue. Will poke around at this.

**Comment by turnstep** [comment]
Raised an issue there: https://github.com/perl5-dbi/dbi/issues/107

**Comment by turnstep** [comment]
Closing here, as it's not something we can easily address at the DBD::Pg level.
