### ISSUE TITLE
META.yaml should be META.yml

### ISSUE THREAD

**Issue by oalders** [bucardo/dbdpg#111]
Please see https://metacpan.org/pod/CPAN::Meta::YAML

I see the file was renamed in https://github.com/bucardo/dbdpg/commit/3d551aebdc4e424395c9c2952ee6189a0eb91e9d but I don't see any explanation for the change in the commit message.

**Comment by oalders** [comment]
See also https://cpants.cpanauthors.org/dist/DBD-Pg

**Comment by turnstep** [comment]
Sigh - so we write out "json" but abbreviate "yaml"? :) Will change it back for the next release.

**Comment by oalders** [comment]
Thanks, @turnstep! I don't make the rules. 🤷🏻‍♂️

**Comment by turnstep** [comment]
Restored as of f21bcb4eb276d168489617e0fbfdd5903dbdab22
