### ISSUE TITLE
DBD::Pg builds are failing to produce MYMETA.json files

### ISSUE THREAD

**Issue by sabbene** [bucardo/dbdpg#113]
Hello,

I see this change from August 2022, https://github.com/bucardo/dbdpg/commit/7856005dd7437ef7b0327cb2d87ca5c8636de53b 

By disabling the generation of the MYMETA.json file package management tools like carmel now fail when installing anything that depends on DBD::Pg.

Is there a reason for disabling the generation of MYMETA.json, and if so is it possible to override that option?

**Comment by esabol** [comment]
Note that PR #112 already has been submitted to address this.

**Comment by Htbaa** [comment]
Spend some time figuring this one out as well as I also had carmel fail. For me sticking to version 3.16.0 of DBD::Pg works for now. Will await the next release that fixes this issue.

**Comment by turnstep** [comment]
Fixed as of b4a924b7ee9678b3be662f7444606206a13f02eb
