### ISSUE TITLE
Simple select of jsonb field returning empty result when field is NULL

### ISSUE THREAD

**Issue by paulprocacci** [bucardo/dbdpg#116]
Simple schema:

```
                          Table "public.volume_objects"
   Column   |     Type     | Collation | Nullable |           Default
------------+--------------+-----------+----------+------------------------------
 id         | bigint       |           | not null |
 state      | object_state |           | not null | 'INITIALIZING'::object_state
 properties | jsonb        |           |          |
Indexes:
    "volume_objects_id_key" UNIQUE CONSTRAINT, btree (id)
```

The following works via both the psql client and perl:

```
lws=# SELECT id FROM volume_objects WHERE state = 'INITIALIZING';
          id
----------------------
 -5313061997377009130
  2474526955579735859
 -1730937477959636728
 -9053604764641466345
 -8739207419327174674
 -6485815955031051872
 -4576737687235381051
 -5974028384145685931
(8 rows)
```

The following only works via the psql utility and not via dbdpg:
```
lws=# SELECT id,properties FROM volume_objects WHERE state = 'INITIALIZING';
          id          |                    properties
----------------------+---------------------------------------------------
 -5313061997377009130 |
  2474526955579735859 |
 -1730937477959636728 |
 -9053604764641466345 | {"Size": "20G", "Compression": "lz4"}
 -8739207419327174674 | {"Size": "20G", "Thick": 0, "Compression": "lz4"}
 -6485815955031051872 | {"Size": "20G", "Thick": 0, "Compression": "lz4"}
 -4576737687235381051 | {"Size": "20G", "Thick": 0, "Compression": "lz4"}
 -5974028384145685931 | {"Size": "20G", "Thick": 0, "Compression": "lz4"}
(8 rows)
```

The following works via both the psql utility and via dbdpg:
```
lws=# SELECT id,properties FROM volume_objects WHERE state = 'INITIALIZING' AND properties IS NOT NULL ;
          id          |                    properties
----------------------+---------------------------------------------------
 -9053604764641466345 | {"Size": "20G", "Compression": "lz4"}
 -8739207419327174674 | {"Size": "20G", "Thick": 0, "Compression": "lz4"}
 -6485815955031051872 | {"Size": "20G", "Thick": 0, "Compression": "lz4"}
 -4576737687235381051 | {"Size": "20G", "Thick": 0, "Compression": "lz4"}
 -5974028384145685931 | {"Size": "20G", "Thick": 0, "Compression": "lz4"}
(5 rows)
```

The simple perl script is:

```
use strict;
use warnings;
use DBI;

my $dbh = DBI->connect("dbi:Pg:dbname=dbname;host=dbhost", 'user', 'pass', {
        AutoCommit => 1,
        RaiseError => 1
});

#my $sth = $dbh->prepare("SELECT id, properties->'Size' FROM volume_objects WHERE state = 'INITIALIZING' AND properties IS NOT NULL");
my $sth = $dbh->prepare("SELECT id, properties->'Size' FROM volume_objects WHERE state = 'INITIALIZING'");
$sth->execute();
while(my $data = $sth->fetchrow()){
  print "Got One!\n";
}
```

Shouldn't dbdpg be able to handle column values that are null?

**Comment by jonjensen** [comment]
@paulprocacci Maybe I'm missing something, but your Perl program is not running the same query that you show in your earlier examples.

Earlier you are doing plain `SELECT id,properties` but in the Perl program you do `SELECT id, properties->'Size'`.

**Comment by paulprocacci** [comment]
That was me fiddling.  The result is the same however.

**Comment by paulprocacci** [comment]
Here's the script which is more inlined with the examples I provided, though it doesn't matter.  The only real difference here is I captured the return value from the ->execute() and displayed it:

```
use strict;
use warnings;
use DBI;

my $dbh = DBI->connect("dbi:Pg:dbname=dbname;host=dbhost", 'user', 'pass', {
        AutoCommit => 1,
        RaiseError => 1
});

my $sth = $dbh->prepare("SELECT id, properties FROM volume_objects WHERE state = 'INITIALIZING'");
my $rc = $sth->execute();
print $rc, "\n";
while(my $data = $sth->fetchrow()){
  print "Got One!\n";
}
```

```
# ./test
8
```

**Comment by jonjensen** [comment]
I think the problem is that you're using the (undocumented) `fetchrow` alias for `fetchrow_array`, but fetching into a scalar `$data` that holds only one value, and `perldoc DBI` says about that:

> If called in a scalar context for a statement handle that has more than one column, it is undefined whether the driver will reurn the value of the first column or the last. So don't do that.  Also, in a scalar context, an "undef" is returned if there are no more rows or if an error occurred. That "undef" can't be distinguished from an "undef" returned because the first field value was NULL. For these reasons you should exercise some caution if you use "fetchrow_array" in a scalar context.

Apparently DBD::Pg is returning the last value, which is a NULL in those rows, so your while loop exits immediately. So it's behaving as DBI allows, but DBI says not to do this.

When I do it this way instead, it works fine:

```perl
while(my ($id, $properties) = $sth->fetchrow()) {
```

Or IMO, better:

```perl
while(my $data = $sth->fetchrow_arrayref) {
```

**Comment by paulprocacci** [comment]
You sir, are correct.  I can't believe I missed that.
Thank you very much for setting me straight.

**Comment by jonjensen** [comment]
No problem. Thanks for the clear examples, easy to try out myself.
