### ISSUE TITLE
Can't load Pg.so on Ubuntu 20.04 and Postgres 8.3.5 - tries to use lo_import_with_oid 

### ISSUE THREAD

**Issue by steve1346** [bucardo/dbdpg#119]
This is what I have, and pretty much stuck with (it's a very large installation with lots of process for any change):
- Ubuntu 20.04
- Postgres 8.3.5
- Perl 5.30.0-9ubuntu0.3
- libdbi-perl 1.643-1ubuntu0.1
- libdbd-pg-perl 3.10.4-1

DBI starts up ok:
    `DBI->available_drivers`
gives me
    `DBM ExampleP File Gofer Mem Pg Proxy Sponge`

But when I try to connect to postgres
    `my $dbh = DBI->connect("dbi:Pg:dbname=$dbname;host=localhost", $user, $passwd);`
the PG driver fails to load:

install_driver(Pg) failed: Can't load '/usr/lib/x86_64-linux-gnu/perl5/5.30/auto/DBD/Pg/Pg.so' for module DBD::Pg: /usr/lib/x86_64-linux-gnu/perl5/5.30/auto/DBD/Pg/Pg.so: undefined symbol: lo_import_with_oid at /usr/lib/x86_64-linux-gnu/perl/5.30/DynaLoader.pm line 193.
 at (eval 8) line 3.
Compilation failed in require at (eval 8) line 3.
Perhaps a required shared library or dll isn't installed where expected
 at ./createHistoryRecords.pl line 25.

BTW the shared libs all seem to be present.

I believe the problem is that lo_import_with_oid is available from postgres 8.4.0 (and I have 8.3.5).

But I thought that dbdpg detected this, and used the older loader? (as of 2015 which seems to be last change in this area).

Am I missing something? Does some environment need to be set?

**Comment by ilmari** [comment]
To use an older version of `libpq` than what's declared in the `libdbd-pg-perl` package ( `libpq5 (>= 8.4~)`) you need to build your own `DBD::Pg`, e.g. using `cpanminus` and `local::lib`.

This is because the decision whether to use the fallback function happens at compile time.
