### ISSUE TITLE
quote.c: 2 * possible bad tests ?

### ISSUE THREAD

**Issue by dcb314** [bucardo/dbdpg#22]
quote.c:377:14: warning: logical 'and' of mutually exclusive tests is always false [-Wlogical-op]
quote.c:379:14: warning: logical 'and' of mutually exclusive tests is always false [-Wlogical-op]

Source code is

        if (
            (ch < 'a' && ch > 'z')
            &&
            (ch < '0' && ch > '9')
            &&
            ch != '_') {

I am not sure that test is ever going to succeed. Suggest code rework.

**Comment by machack666** [comment]
I think you're correct; I assume the inner && should be || in this case to test what the comment is indicating it is.  Will fix and test.

**Comment by machack666** [comment]
Fixed in 5fa8b72.
