### ISSUE TITLE
Determine column types of query result

### ISSUE THREAD

**Issue by jef-sure** [bucardo/dbdpg#24]
I have a problem with discovering column types of query result: https://gist.github.com/jef-sure/9a28e7c12f0c03d32080456afd4dafd3

**Comment by machack666** [comment]
Hi @jef-sure; what version of PostgreSQL and DBD::Pg?

**Comment by jef-sure** [comment]
DBD::Pg -- 3.6.0,
PostgreSQL -- 9.5.6
perl -- 5.22.3

**Comment by jef-sure** [comment]
I just tried PostgreSQL 9.6.3 -- the same problem.

**Comment by machack666** [comment]
Hi @jef-sure, I suspect this has to do with the mapping of the column types as returned by libpq, not DBD::Pg.  Can you test using explicit type casts for the column types and see if that returns as expected?

**Comment by jef-sure** [comment]
I don't quite understand to what types cast columns. Using `DBD::PgPP` I was able to retrieve following info:
```
                 'row_description' => [
                                        {
                                          'name' => 'id',
                                          'modifier' => 4294967295,
                                          'type' => 23,
                                          'size' => 4
                                        },
                                        {
                                          'size' => 65535,
                                          'type' => 25,
                                          'modifier' => 4294967295,
                                          'name' => 'title'
                                        },
                                        {
                                          'size' => 1,
                                          'type' => 16,
                                          'modifier' => 4294967295,
                                          'name' => 'completed'
                                        },
                                        {
                                          'size' => 65535,
                                          'type' => 3802,
                                          'modifier' => 4294967295,
                                          'name' => 'misc'
                                        }
                                      ],
```
I hope this helps.

**Comment by machack666** [comment]
hmm, those type ids are mapping to the correct/expected type in `Pg.xs`, so I'm not sure why that's happening.  I'll look a little deeper at your test case and see what we can figure out.

**Comment by turnstep** [comment]
So this took a bit of tracking, but I think it is because we switched the mapping for text aka PG_TEXT from SQL_VARCHAR to SQL_LONGVARCHAR in types.c, but did not make an explicit reverse mapping in Pg.pm. Please see if 84e9ebdf5c44358144f3b85a3cc6df398dad1e35 fixes your test case.

**Comment by jef-sure** [comment]
It was a step in right direction! :) Now it recoginzes **text** type but **jsonb** is still **unknonw**. 

```perl
print_columns("todo",               table_columns("todo"));
print_columns("select * from todo", query_columns("select * from todo"));
```
reports now:
```
todo:
id: integer
title: text
completed: boolean
order: integer
misc: jsonb

select * from todo:
id: int4
title: text
completed: bool
order: int4
misc: unknown
```

**Comment by turnstep** [comment]
jsonb (and json) do not map back to standard SQL/ODBC types, so it's unlikely it will ever produce the desired results via $sth->{TYPE}. TYPE_NAME is a little more loose in what it can return. However, if you simply want the non-standard names, just call $sth->{pg_type}->[$cn];

**Comment by turnstep** [comment]
Closing for now - feel free to re-open if needed.
