### ISSUE TITLE
Crash in the absence of client_encoding

### ISSUE THREAD

**Issue by johto** [bucardo/dbdpg#29]
DBD::Pg crashes the Perl process in pg_db_detect_client_encoding_utf8() if the server doesn't send client_encoding as a startup parameter.  This is fine if you're connecting to a vanilla postgres, but less so if you're connecting to one which only speaks the wire protocol but doesn't care as much about encodings and such.  I'm not sure whether this should be considered a bug or not, but I thought I'd open a ticket anyway.  Segmentation faults certainly don't look nice.

**Comment by machack666** [comment]
Looks like this is due to not checking for `NULL` in a `PQparameterStatus()` call.  Will push a fix for this.

**Comment by machack666** [comment]
Fixed in f29a19e, also found/fixed a similar unlikely crash as well.

Thanks for the report.
