### ISSUE TITLE
Accessing ->state appears to be leaking memory

### ISSUE THREAD

**Issue by johto** [bucardo/dbdpg#30]
An example program demonstrating the problem:

```Perl
#!/usr/bin/perl

use strict;
use warnings;

use DBI;
use DBD::Pg;

my @connect = ("dbi:Pg:", '', '', {pg_enable_utf8 => 1, RaiseError => 0, PrintError => 0, AutoCommit => 1});
my $dbh = DBI->connect(@connect) or die "foo: ".$DBI::errstr;

for (;;) {
    my $stmt = $dbh->prepare(q{SELECT 1 / 0});
    if (!$stmt) {
        die "wtf: ".$dbh->errstr;
    }
    my $rv = $stmt->execute();
    if (defined $rv) {
        die "oh no";
    }
    for (my $j = 0; $j < 10000; ++$j) {
        my $foo = $dbh->state;
    }
}
```

I've tested this against the Ubuntu version of 2.19.3 and 3.6.2 they both seem to be having the same problem.  I'm no XS expert, but the lack of sv_2mortal() here:

```C
void state(sth)
SV *sth;
    CODE:
        D_imp_sth(sth);
        D_imp_dbh_from_sth;
        ST(0) = strEQ(imp_dbh->sqlstate,"00000") ? &PL_sv_no :
           /* ----> */ newSVpv(imp_dbh->sqlstate, 5);
```

looks suspicious compared to all the other assignments to ST(0).  The problem exists for the state method on both the statement and the database handles.

**Comment by ilmari** [comment]
Thanks, I can confirm the leak, and that adding `sv_2mortal()` fixes it. Pushed as 5039252e17cab7638b4a33bfd3e08ec9a4189419.
