### ISSUE TITLE
Placeholders must begin with ':' when using the ":foo" style

### ISSUE THREAD

**Issue by dk** [bucardo/dbdpg#38]
Legacy code using ":foo" style selects fails with this error. The code is as follows:

```
$dbh->selectall_array('SELECT now where 1 = :id', {}, $id);
```

Since the call is issued as

```
	sv_setiv(idx, i);
	if (!dbd_bind_ph(sth, imp_sth, idx, value, 0, Nullsv, FALSE, 0)) {
```

with idx being the third parameter with the integer, and the third parameter is supposed to be a ":foo" string inside dbd_bind_ph, I can't find a way how this supposed to be working.

**Comment by ilmari** [comment]
When using named placeholders, you must bind them by name using `bind_param`:

```perl
my $sth = $dbh->prepare('SELECT now() where 1 = :id');
$sth->bind_param(':id', $id);
$sth->execute;
$sth->fetchrow_array; # '2019-03-30 22:20:44.600588+00'
```

**Comment by dk** [comment]
thank you!
