### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by aried3r** [bucardo/dbdpg#45]
Hey! I saw that you recently released version 3.8.0 that contains some fixes for PostgreSQL 11. I tried to install the current version using

```console
$ cpan DBD::Pg
```

but it only found 3.7.4, which is also what the [metacpan website](https://metacpan.org/release/DBD-Pg) tells me.

Are there any plans to release it to cpan soon? Cheers!

**Comment by turnstep** [comment]
3.8.0 has been released :)
