### ISSUE TITLE
AutoCommit gets enabled on COMMIT failure

### ISSUE THREAD

**Issue by 17dec** [bucardo/dbdpg#71]
This one caught me by surprise. I've no clue if this is intended behavior nor whether this behavior lies with DBD::Pg or with how Postgres itself handles transactions, so I'm just going to throw it out here and see if anyone can provide further insight.

**Observed behavior:**
`AutoCommit` is suddenly enabled on the connection if a `$dbh->commit()` fails.

**Expected behavior:**
A failed commit is equivalent to a `ROLLBACK` and leaves `AutoCommit` alone.

**Quick test script:**
```perl
#!/usr/bin/perl
use DBI;

my $dbh = DBI->connect(undef, undef, undef, { AutoCommit => 0 });

# Need to get a COMMIT to fail, a deferred constraint will do the trick.
$dbh->do('CREATE TABLE dbdpg_test (id int primary key, val integer)');
$dbh->do('ALTER TABLE dbdpg_test ADD CONSTRAINT ref FOREIGN KEY (val) REFERENCES dbdpg_test(id) DEFERRABLE INITIALLY DEFERRED');

# This succeeds, constraint is deferred.
$dbh->do('INSERT INTO dbdpg_test VALUES (1,2)');

# This fails, as expected.
$dbh->commit;

# The above (correctly) prints the following error:
#
#    DBD::Pg::db commit failed: ERROR:  insert or update on table "dbdpg_test" violates foreign key constraint "ref"
#    DETAIL:  Key (val)=(2) is not present in table "dbdpg_test".

# This, on the other hand, is unexpected:
print "AutoCommit is now enabled\n" if $dbh->{AutoCommit};
```

**Comment by turnstep** [comment]
This should be solved now.

**Comment by 17dec** [comment]
git master works for me, thanks!

**Comment by esabol** [comment]
This issue wasn’t mentioned in the `Changes` file in 3.13.0. Oversight?

**Comment by turnstep** [comment]
Ah, sorry about that. It is in the release notes for DBD::Pg version 3.12.3, but has the wrong Github issue number (listed as 57, which is not solved yet, but should be this one, issue 71). Will update the Changes file.

**Comment by esabol** [comment]
Ah, cool. Thank you!
