### ISSUE TITLE
Add support for passing application_name into connect

### ISSUE THREAD

**Issue by mrmuskrat** [bucardo/dbdpg#77]
When I try to pass application_name as a connection parameter as documented in the [libpq-connect docs](https://www.postgresql.org/docs/current/libpq-connect.html) I get an error:
invalid connection option "application_name"

I know... It's not documented to work in DBD::Pg but it should. Java and Python can set it and Perl should be able to as well!

If I can set $ENV{PGAPPNAME} soon enough in the process that usually works but it's not always feasible to do so.

In the meantime, I'm issuing a `SET application_name = 'foo'` after connection (via DBIx::Class::Storage::DBI's [on_connect_do/connect_info](https://metacpan.org/pod/DBIx::Class::Storage::DBI#on_connect_do1), scroll up to see the real-life examples).

**Comment by mrmuskrat** [comment]
It should also work if with a service connection file too.

**Comment by ilmari** [comment]
Which version of DBD::Pg and libpq are you using? That error message is from libpq, but it has supported `application_name` since version 9.0.

```
1> my $dbh = DBI->connect("dbi:Pg:application_name=reply")
$res[1] = bless( {}, 'DBI::db' )

2> $dbh->selectrow_array('show application_name')
$res[2] = 'reply'

3> DBD::Pg->VERSION 
$res[3] = '3.13.0'

6> $dbh->{pg_lib_version}
$res[4] = 120003
```

**Comment by mrmuskrat** [comment]
I feel like an idiot now. We're moving our applications around and I should have checked the original containers. We somehow have an older version of libpq where I was trying to test and I didn't notice.

Sorry about that.
