### ISSUE TITLE
Tests fail when run as root

### ISSUE THREAD

**Issue by mjaix** [bucardo/dbdpg#79]
... due to File::Temp::tempdir being used without having run 'require File::Temp' first:

...
t/01connect.t .......... 
Dubious, test returned 1 (wstat 256, 0x100)
No subtests run 
t/01constants.t ........ ok
Please wait, creating new database (version 10.16) for testing
Undefined subroutine &File::Temp::tempdir called at t/dbdpg_test_setup.pl line 376.
t/02attribs.t ..........
...

**Comment by turnstep** [comment]
Thanks, will fix this up!

**Comment by turnstep** [comment]
Fixed in b25ecc46de32b6bbe955f32d6dbd1b95c58ac755

**Comment by dcermak** [comment]
@turnstep Thanks for the quick fix! Could you please make a new release including this patch so that `sudo cpanm DBD::Pg` works?

**Comment by esabol** [comment]
@mjaix : Is this issue resolved in the 3.15.1 release? If so, please close.

**Comment by turnstep** [comment]
No reply, so closing and assumed fixed for original poster
