### ISSUE TITLE
"execute called with an unbound placeholder" with functions and array slice

### ISSUE THREAD

**Issue by philip-stoev** [bucardo/dbdpg#81]
The following query:

```
SELECT a[1:abs(1)];
```

can not be run using ```DBD-Pg-3.15``` . The following error is returned:

```
Postgres 09.05.0000:XX000:execute called with an unbound placeholder
```

The same query runs fine using the ```psql``` client. I think the perl driver thinks that the ```1:abs``` part denotes a placeholder , whereas it should have been passed verbatim to the database server.

The workaround is to insert a space after the ```:``` character.

**Comment by esabol** [comment]
The `:abs` is interpreted as a named placeholder. See https://metacpan.org/pod/DBD::Pg#Placeholders

You can turn off this feature like so:
```Perl
$dbh->{pg_placeholder_nocolons} = 1;
```
