### ISSUE TITLE
Version 3.14.0 and later Cannot Compile against Postgres 9.2 or earlier

### ISSUE THREAD

**Issue by theory** [bucardo/dbdpg#84]
Looks like 751f5ca may have broken DBD::Pg for 9.2 and lower. Was it the intention to drop support prior to 9.3, or was the intent to support `pg_lo_tell64` and friends only on 9.3 but still support 9.2 and earlier overall?

Spotted as I was adding tests for older versions of Postgres to Sqitch, where [9.2 failed](https://github.com/sqitchers/sqitch/runs/3921388916?check_suite_focus=true) with this error among others:

```
dbdimp.c:43:14: error: conflicting types for ‘lo_lseek64’
 unsigned int lo_lseek64(PGconn *conn, int fd, unsigned int offset, int whence);
               ^~~~~~~~~~
 In file included from Pg.h:35,
                 from dbdimp.c:14:
/usr/include/postgresql/libpq-fe.h:620:17: note: previous declaration of ‘lo_lseek64’ was here
```

**Comment by theory** [comment]
@df7cb can you comment on this? The `pg-start` script uses

```
apt.postgresql.org.sh -i -v 9.2
```

to instal the version. Is there a way for that script to also install libpq such that it's easily findable? Or do I need to figure out how to add `/usr/include/postgresql/9.2/bin` to the path?

**Comment by ilmari** [comment]
As I mentioned in my original coment:

> To get older `libpq` versions you need to add the version-specific suite to the `sources.list` line e.g.
> 
> ```
> deb http://apt.postgresql.org/pub/repos/apt/ sid-pgdg-testing main 9.2
> ```
> 
> and install the specific version with `apt install libq{5,-dev}=9.2.*`.

**Comment by df7cb** [comment]
Can't you use PG_VERSION_NUM instead? That will point to the more recent libpq version (at least in /usr/include/postgresql/pg_config.h), even if pg_config is older.

**Comment by theory** [comment]
Decided to look at this again today, and go it to work simply by adding the `-t` option to [`apt.postgresql.org.sh`] once I noticed it in [the source](https://salsa.debian.org/postgresql/postgresql-common/-/raw/master/pgdg/apt.postgresql.org.sh): It configures `pgdg-testing` instead of `pgdg`. And now [it's all green](https://github.com/sqitchers/sqitch/actions/runs/5708655951).

**Comment by turnstep** [comment]
Glad it is working now. Can we close this, or do we need a doc tweak?

**Comment by theory** [comment]
I don’t see why not
