### ISSUE TITLE
cpan based install failing on signature issue

### ISSUE THREAD

**Issue by nodenineinc** [bucardo/dbdpg#87]
cpan[1]> install DBD::Pg                   
Reading '/usr/cpan/Metadata'
  Database was generated on Sat, 20 Nov 2021 19:17:03 GMT
Running install for module 'DBD::Pg'
Fetching with LWP:
http://www.cpan.org/authors/id/T/TU/TURNSTEP/DBD-Pg-3.15.0.tar.gz
WARNING: This key is not certified with a trusted signature!
Primary key fingerprint: 2E66 557A B97C 19C7 91AF  8E20 328D A867 450F 89EC
Signature for /usr/cpan/sources/authors/id/T/TU/TURNSTEP/CHECKSUMS ok
Checksum for /usr/cpan/sources/authors/id/T/TU/TURNSTEP/DBD-Pg-3.15.0.tar.gz ok
Scanning cache /usr/cpan/build for sizes
............................................................................DONE
gpg: Signature made Thu 13 Aug 2020 06:33:09 AM PDT
gpg:                using DSA key 2529DF6AB8F79407E94445B4BC9B906714964AC8
gpg: Can't check signature: No public key
--- SIGNATURE Sun Jan 10 09:00:07 2021
+++ (current) Sat Nov 20 13:35:17 2021
@@ -1,44 +1,44 @@
 SHA256 e4c6f4cdc9560a09492f196fc9a180867fab12742d7d05052d9842b395c6a9eb .dir-locals.el
-SHA256 599f3c02300e2558e32c2b1ea52802b6585b5e0227036c0675404e598fc163e0 .perlcriticrc
-SHA256 e8d3a038d88fb019bb96983f0c52125f86a4c3465466a20612bf4958ace70ed5 CONTRIBUTING.md
-SHA256 fb932bfd5dc64c16b1768ea293708c11c22c85b85bcb8dc85e33ad649e281f16 Changes
+SHA256 e23f1fcd188734118fec21c5c5525307568b67a0ba97308956f0dc7d0ad969a9 .perlcriticrc
+SHA256 56479e9cf7c00a72bc5458593463a5a6e5481f74f3a4be5ef94129e01c3e2f91 CONTRIBUTING.md
+SHA256 afbf4bb6502c8c1ed789fec3d74bce0253f2b3392fe3034dc663bcf42a61bf87 Changes
 SHA256 d52a34724b2e3c40ffa2b3b378b574b9e3db27bc3132c88e0be3675f93f378a5 LICENSES/artistic.txt
 SHA256 ab15fd526bd8dd18a9e77ebc139656bf4d33e97fc7238cd11bf60e2b9b8666c6 LICENSES/gpl-2.0.txt
 SHA256 e15fb8180cca35de2c3de6854e5cf23152a7733dfa89640825ae13f6f83b0e72 MANIFEST
 SHA256 f41d8891a80fa4f3fbf1c96fc745a2c8ecc0497045a9ad55daea54d5ffcb4683 MANIFEST.SKIP
-SHA256 a16a5a33fe23f3d01757d9f451ac21febc7adf966ae6e7b8fc08d744c938e272 META.yml
-SHA256 c2b3276297eb3eef4ebb3b1dbf7d67cc66d373ef32a87a28124f74cfe1c7cb5d Makefile.PL
-SHA256 d7d68c574b9469375f92aaf0bfd0e539f635a45da869f91390fdc401b1ccaefb Pg.h
-SHA256 73115a4af943b78495686c6eb6df2a8e830319ba2413277cd78920c99f549143 Pg.pm
-SHA256 ec04611ed1b769de30887bbea5d916ea1535e26beef296dcb0506a484cfd96c4 Pg.xs
-SHA256 3d883a2ac45eabb5520590098a07cb405e1109c41efe0444f205c0192d1b4a24 README
-SHA256 230949b9f9e12a116f1b776946ecad0f249cf2577ed1ac1918662fca06b9428c README.dev
+SHA256 4c329649a9622cee52f6bf51bde833c0d965a034287b39c43f9ac4eca4d22615 META.yml
+SHA256 e98c97637bd57f099d35953dcf5d467afdc357a386e2ab8926bddd2f42b8c3e8 Makefile.PL
+SHA256 829befc6322c3e371eb026d23d589ed1f5334d765b90026af53c6b1c20f9ec0a Pg.h
+SHA256 411d893d7fbb9041d19d5d1fd664da5d856f86319032b316349c36d89464918c Pg.pm
+SHA256 03687d0817f1cd7d24ddc51d13aad83338b95e36f1b8496533c326dbb4c96c96 Pg.xs
+SHA256 75b266bc2d00e5a4cf43659a468db3a1347f0003ff01d6630aa870483e5a668b README
+SHA256 abb4dc534d316fd2adedd246734110178aad80af2d3a65119d5a816f1cb37933 README.dev
 SHA256 a1d224603fe3a343ba0a0f40086065c81d57fbebc734b5382b0d359da16bdd94 README.win32
-SHA256 ce798149ee5bf517fb76d6a652c3e4619bfda6ed706df068f2d0fd1f05ed259c TODO
-SHA256 7756584f0e0d909ae0ce1b156d638f3129fe756d144a9b5d7812a31c8e9188b2 dbdimp.c
-SHA256 72c7b368ca468cd1df7f5593770ac72b7680aeb6c4924f9c5b5f17b774619ead dbdimp.h
+SHA256 a4476689aa6467b0f08097e1f72d549eac1ad790d2c56ef649341c0da08558e9 TODO
+SHA256 b994e59afeaf30e5f8285a8194b3c39a72b68f7007b572a9245c4d1bffeadce4 dbdimp.c
+SHA256 e8652b039cc5ad6b2d61c5a9236e8a8f720c48c0eaad92e6d8ba8196578f01c8 dbdimp.h
 SHA256 9e53f7f41aaaf1b540e2784756ef6f16f61b63df0d9956483aded3c49b6e0f48 dbivport.h
-SHA256 f639833c96bb032135480bfac7802c6adf6ab0d5964a9222fb7347ac3630a807 lib/Bundle/DBD/Pg.pm
-SHA256 c945a57d774dc5bb789f2af67892c749f8c4d42b75967c9aab4bc436ed635a90 quote.c
+SHA256 d33043fa8f0e0b9cfaea78058062a14a39e5e0a22dbd8f0a6c7e2fa98b1b8efa lib/Bundle/DBD/Pg.pm
+SHA256 50df4dba2b04d9dbe27fe64e48e2732a58de8a01013143aa18b4f9d87d26da21 quote.c
 SHA256 1ee43f02036bbb68c151903c2718c483ed223aff6cc93fb1408a9158adad9136 quote.h
 SHA256 49950c2c882018916ef89b59a1707b732064eb3bb6acb6a350111e1dc81000b8 t/00_signature.t
 SHA256 4a95e025f903ed2d6a0aa4470f46f075d4692b9a21bd1d316ead19fb9cabd2dd t/00basic.t
-SHA256 19e8f71d48ab56d22ec1ba1551a4e5db68c113001e8ac66a6d6250c0e1799a8e t/01connect.t
-SHA256 4e506c9d0ebcd1231cdcbde147b66eba825c85bb5e708f0575ee5df57379944f t/01constants.t
-SHA256 e0075d89da43127ea1b0011dadbf5174660c52df6ffc18a40afe02d641a2d2b6 t/02attribs.t
-SHA256 2495fb2858d0f805f1e7ca93dda0760b2b8c36c4e637c43828edc1c06433664e t/03dbmethod.t
-SHA256 d3d111252be1dd32001e7d5aa0b89f5b623aa5cf0a541b94de9742b5ef48fb5f t/03smethod.t
-SHA256 c5bffc4e2284ee49d0be6a9fd4290e1139a14449ee7c651bf4252e722dfe0de8 t/04misc.t
+SHA256 0bea371cef24f361913e7865d043a314cdeaffff104f3792b00770e93b2eadcc t/01connect.t
+SHA256 50ce2e03b34dfc5e45c0af8f4078825b1ed449d201f165d8d05453762110ae72 t/01constants.t
+SHA256 4a57102776fa991abbdf52427f14b2200b0de9415495f625bbb4a89b3f9c99c0 t/02attribs.t
+SHA256 2c8ae070dcc5bd2b716be9094011de898ae79cc6df72fbea19672bce16f9afd9 t/03dbmethod.t
+SHA256 f6769b211e07e4bdeaf6e8b70c91dc2568758a92011f34d1315f9ee73478a82e t/03smethod.t
+SHA256 a3767a1b6e9adf62ec73f9d38b8bca151eb2fd872d42c2f77aeaef72178b1c56 t/04misc.t
 SHA256 d30d52695492fbcb2d051c48d0d3afb621b0d5b29d876208b5fd79c5bc50b3fa t/06bytea.t
 SHA256 f172234f057e485a8d5838db6986dbda18f4fe81fcf9ad0885728b8aec31b852 t/07copy.t
 SHA256 2e50d0d3cea8c90882a06b99537d7aebcb8d8f062a775831d4b07056e832c4c1 t/08async.t
 SHA256 13939607c75558e63395d0d77e78ed2485cd97b2e3d6559e72ec45bffdf333e4 t/09arrays.t
 SHA256 97254af96ad61b3306b55ea687db6e5439e18a692f763aabc74bebe85e0c04c9 t/10_pg_error_field.t
-SHA256 a30dfbe57581c3e82e2ebf32f90a96493c5868c8aceaf2f8ef90c4c82173f299 t/12placeholders.t
+SHA256 9a4b3ba6e7931c21fdeab0225777de3512f68e58fc98305da5073694c5f84afe t/12placeholders.t
 SHA256 982a438ec73b0428c263ed4608d82fd466a1668cfd4095c69d93ae002486368c t/20savepoints.t
 SHA256 6bdf1b5d0bdc049bf8ff8a66d36fc41dfaea2d15e8550dc7e19ce152aa73c918 t/30unicode.t
 SHA256 16b874ee36dcedc566b6c9b4c8142173e3a6babc660721939756d8a0a7d697f2 t/99cleanup.t
-SHA256 543c7990a7abd6b80889393209924c8c0d7d45509b73846d053801980394fc70 t/dbdpg_test_setup.pl
+SHA256 9cf22ac29150f372db11805cbe97a31d2d4cb5a1e62d93cd611ecde99f01f594 t/dbdpg_test_setup.pl
 SHA256 50be982cc158a60f531674a593a55a05cac2f358b865e0cbcc6fc86285f719c0 t/lib/App/Info.pm
 SHA256 e930aed2b35b6dd2504c8652f8037ce8e98454e0105babeca46ee133996fa084 t/lib/App/Info/Handler.pm
 SHA256 bda949f555f730887b54d12627fdf17f290b245cf03ca14b7c4fc5b996c33884 t/lib/App/Info/Handler/Print.pm
@@ -47,7 +47,7 @@
 SHA256 7ea6b4ee4b5cd6b0b44939544138503ede324c8a85a06a8b51334d62c1298669 t/lib/App/Info/RDBMS/PostgreSQL.pm
 SHA256 36b5ac866344827a286687f036ed2702d2ccdee450ad1581a64995523b6df976 t/lib/App/Info/Request.pm
 SHA256 6725541fdeb205716695fca6ff90f77d4e37e33f7d2cefab0b8f946876f646f9 t/lib/App/Info/Util.pm
-SHA256 e37a46dd0a9b569e89de9549f3a00d90327b348f3fc67d28fb8a0508cbb2a498 testme.tmp.pl
-SHA256 f9567669852e55092c612e4f63a2e0540472947555fc8a57f429fa8383970c49 types.c
-SHA256 064c0dc289767d594b1272525c28219fc7304fe2aa815b9b29a043c90ec51c12 types.h
+SHA256 eedc5a43373937237f35a298f6945d87dc0144c91eaae3eea4a19e79d0ae462c testme.tmp.pl
+SHA256 6b5ec7d1edf69f91407a7d5efd75e4dcde8a583434301fa48fe1ff50ffb1129d types.c
+SHA256 789d430468f518ec7d46114bae5fcb11f08f29bd573999b02712ac8b6e75a72a types.h
 SHA256 4628f92764bdb3e2b04bda7f30fc497231fbbf80dfd24cc09ee3df2e6d6d4387 win32.mak
==> MISMATCHED content between SIGNATURE and distribution files! <==

Signature invalid for distribution file. Please investigate.

I'd recommend removing
/usr/cpan/sources/authors/id/T/TU/TURNSTEP/DBD-Pg-3.15.0.tar.gz. Some error
occurred   while checking its signature, so it could	    be invalid.
Maybe you have configured	     your 'urllist' with a bad URL. Please
check this array with 'o conf urllist' and retry. Or	    examine the
distribution in a subshell. Try
  look TURNSTEP/DBD-Pg-3.15.0.tar.gz
and run
  cpansign -v
  TURNSTEP/DBD-Pg-3.15.0.tar.gz
  Did not pass the signature test.
Failed during this command:
 TURNSTEP/DBD-Pg-3.15.0.tar.gz                : signature_verify NO

cpan[2]> o conf urllist
    urllist           
	0 [http://www.cpan.org/]
Type 'o conf' to view all configuration items

/usr/cpan/build/DBD-Pg-3.15.0-1# cpansign -v
Executing gpg --verify --batch --no-tty --keyserver=hkp://pool.sks-keyservers.net:11371 /tmp/Fmha4Yg0la
gpg: Signature made Thu 13 Aug 2020 06:33:09 AM PDT
gpg:                using DSA key 2529DF6AB8F79407E94445B4BC9B906714964AC8
gpg: Can't check signature: No public key
--- SIGNATURE Sun Jan 10 09:00:07 2021
+++ (current) Sat Nov 20 13:39:01 2021
@@ -1,44 +1,44 @@
 SHA256 e4c6f4cdc9560a09492f196fc9a180867fab12742d7d05052d9842b395c6a9eb .dir-locals.el
-SHA256 599f3c02300e2558e32c2b1ea52802b6585b5e0227036c0675404e598fc163e0 .perlcriticrc
-SHA256 e8d3a038d88fb019bb96983f0c52125f86a4c3465466a20612bf4958ace70ed5 CONTRIBUTING.md
-SHA256 fb932bfd5dc64c16b1768ea293708c11c22c85b85bcb8dc85e33ad649e281f16 Changes
+SHA256 e23f1fcd188734118fec21c5c5525307568b67a0ba97308956f0dc7d0ad969a9 .perlcriticrc
+SHA256 56479e9cf7c00a72bc5458593463a5a6e5481f74f3a4be5ef94129e01c3e2f91 CONTRIBUTING.md
+SHA256 afbf4bb6502c8c1ed789fec3d74bce0253f2b3392fe3034dc663bcf42a61bf87 Changes
 SHA256 d52a34724b2e3c40ffa2b3b378b574b9e3db27bc3132c88e0be3675f93f378a5 LICENSES/artistic.txt
 SHA256 ab15fd526bd8dd18a9e77ebc139656bf4d33e97fc7238cd11bf60e2b9b8666c6 LICENSES/gpl-2.0.txt
 SHA256 e15fb8180cca35de2c3de6854e5cf23152a7733dfa89640825ae13f6f83b0e72 MANIFEST
 SHA256 f41d8891a80fa4f3fbf1c96fc745a2c8ecc0497045a9ad55daea54d5ffcb4683 MANIFEST.SKIP
-SHA256 a16a5a33fe23f3d01757d9f451ac21febc7adf966ae6e7b8fc08d744c938e272 META.yml
-SHA256 c2b3276297eb3eef4ebb3b1dbf7d67cc66d373ef32a87a28124f74cfe1c7cb5d Makefile.PL
-SHA256 d7d68c574b9469375f92aaf0bfd0e539f635a45da869f91390fdc401b1ccaefb Pg.h
-SHA256 73115a4af943b78495686c6eb6df2a8e830319ba2413277cd78920c99f549143 Pg.pm
-SHA256 ec04611ed1b769de30887bbea5d916ea1535e26beef296dcb0506a484cfd96c4 Pg.xs
-SHA256 3d883a2ac45eabb5520590098a07cb405e1109c41efe0444f205c0192d1b4a24 README
-SHA256 230949b9f9e12a116f1b776946ecad0f249cf2577ed1ac1918662fca06b9428c README.dev
+SHA256 4c329649a9622cee52f6bf51bde833c0d965a034287b39c43f9ac4eca4d22615 META.yml
+SHA256 e98c97637bd57f099d35953dcf5d467afdc357a386e2ab8926bddd2f42b8c3e8 Makefile.PL
+SHA256 829befc6322c3e371eb026d23d589ed1f5334d765b90026af53c6b1c20f9ec0a Pg.h
+SHA256 411d893d7fbb9041d19d5d1fd664da5d856f86319032b316349c36d89464918c Pg.pm
+SHA256 03687d0817f1cd7d24ddc51d13aad83338b95e36f1b8496533c326dbb4c96c96 Pg.xs
+SHA256 75b266bc2d00e5a4cf43659a468db3a1347f0003ff01d6630aa870483e5a668b README
+SHA256 abb4dc534d316fd2adedd246734110178aad80af2d3a65119d5a816f1cb37933 README.dev
 SHA256 a1d224603fe3a343ba0a0f40086065c81d57fbebc734b5382b0d359da16bdd94 README.win32
-SHA256 ce798149ee5bf517fb76d6a652c3e4619bfda6ed706df068f2d0fd1f05ed259c TODO
-SHA256 7756584f0e0d909ae0ce1b156d638f3129fe756d144a9b5d7812a31c8e9188b2 dbdimp.c
-SHA256 72c7b368ca468cd1df7f5593770ac72b7680aeb6c4924f9c5b5f17b774619ead dbdimp.h
+SHA256 a4476689aa6467b0f08097e1f72d549eac1ad790d2c56ef649341c0da08558e9 TODO
+SHA256 b994e59afeaf30e5f8285a8194b3c39a72b68f7007b572a9245c4d1bffeadce4 dbdimp.c
+SHA256 e8652b039cc5ad6b2d61c5a9236e8a8f720c48c0eaad92e6d8ba8196578f01c8 dbdimp.h
 SHA256 9e53f7f41aaaf1b540e2784756ef6f16f61b63df0d9956483aded3c49b6e0f48 dbivport.h
-SHA256 f639833c96bb032135480bfac7802c6adf6ab0d5964a9222fb7347ac3630a807 lib/Bundle/DBD/Pg.pm
-SHA256 c945a57d774dc5bb789f2af67892c749f8c4d42b75967c9aab4bc436ed635a90 quote.c
+SHA256 d33043fa8f0e0b9cfaea78058062a14a39e5e0a22dbd8f0a6c7e2fa98b1b8efa lib/Bundle/DBD/Pg.pm
+SHA256 50df4dba2b04d9dbe27fe64e48e2732a58de8a01013143aa18b4f9d87d26da21 quote.c
 SHA256 1ee43f02036bbb68c151903c2718c483ed223aff6cc93fb1408a9158adad9136 quote.h
 SHA256 49950c2c882018916ef89b59a1707b732064eb3bb6acb6a350111e1dc81000b8 t/00_signature.t
 SHA256 4a95e025f903ed2d6a0aa4470f46f075d4692b9a21bd1d316ead19fb9cabd2dd t/00basic.t
-SHA256 19e8f71d48ab56d22ec1ba1551a4e5db68c113001e8ac66a6d6250c0e1799a8e t/01connect.t
-SHA256 4e506c9d0ebcd1231cdcbde147b66eba825c85bb5e708f0575ee5df57379944f t/01constants.t
-SHA256 e0075d89da43127ea1b0011dadbf5174660c52df6ffc18a40afe02d641a2d2b6 t/02attribs.t
-SHA256 2495fb2858d0f805f1e7ca93dda0760b2b8c36c4e637c43828edc1c06433664e t/03dbmethod.t
-SHA256 d3d111252be1dd32001e7d5aa0b89f5b623aa5cf0a541b94de9742b5ef48fb5f t/03smethod.t
-SHA256 c5bffc4e2284ee49d0be6a9fd4290e1139a14449ee7c651bf4252e722dfe0de8 t/04misc.t
+SHA256 0bea371cef24f361913e7865d043a314cdeaffff104f3792b00770e93b2eadcc t/01connect.t
+SHA256 50ce2e03b34dfc5e45c0af8f4078825b1ed449d201f165d8d05453762110ae72 t/01constants.t
+SHA256 4a57102776fa991abbdf52427f14b2200b0de9415495f625bbb4a89b3f9c99c0 t/02attribs.t
+SHA256 2c8ae070dcc5bd2b716be9094011de898ae79cc6df72fbea19672bce16f9afd9 t/03dbmethod.t
+SHA256 f6769b211e07e4bdeaf6e8b70c91dc2568758a92011f34d1315f9ee73478a82e t/03smethod.t
+SHA256 a3767a1b6e9adf62ec73f9d38b8bca151eb2fd872d42c2f77aeaef72178b1c56 t/04misc.t
 SHA256 d30d52695492fbcb2d051c48d0d3afb621b0d5b29d876208b5fd79c5bc50b3fa t/06bytea.t
 SHA256 f172234f057e485a8d5838db6986dbda18f4fe81fcf9ad0885728b8aec31b852 t/07copy.t
 SHA256 2e50d0d3cea8c90882a06b99537d7aebcb8d8f062a775831d4b07056e832c4c1 t/08async.t
 SHA256 13939607c75558e63395d0d77e78ed2485cd97b2e3d6559e72ec45bffdf333e4 t/09arrays.t
 SHA256 97254af96ad61b3306b55ea687db6e5439e18a692f763aabc74bebe85e0c04c9 t/10_pg_error_field.t
-SHA256 a30dfbe57581c3e82e2ebf32f90a96493c5868c8aceaf2f8ef90c4c82173f299 t/12placeholders.t
+SHA256 9a4b3ba6e7931c21fdeab0225777de3512f68e58fc98305da5073694c5f84afe t/12placeholders.t
 SHA256 982a438ec73b0428c263ed4608d82fd466a1668cfd4095c69d93ae002486368c t/20savepoints.t
 SHA256 6bdf1b5d0bdc049bf8ff8a66d36fc41dfaea2d15e8550dc7e19ce152aa73c918 t/30unicode.t
 SHA256 16b874ee36dcedc566b6c9b4c8142173e3a6babc660721939756d8a0a7d697f2 t/99cleanup.t
-SHA256 543c7990a7abd6b80889393209924c8c0d7d45509b73846d053801980394fc70 t/dbdpg_test_setup.pl
+SHA256 9cf22ac29150f372db11805cbe97a31d2d4cb5a1e62d93cd611ecde99f01f594 t/dbdpg_test_setup.pl
 SHA256 50be982cc158a60f531674a593a55a05cac2f358b865e0cbcc6fc86285f719c0 t/lib/App/Info.pm
 SHA256 e930aed2b35b6dd2504c8652f8037ce8e98454e0105babeca46ee133996fa084 t/lib/App/Info/Handler.pm
 SHA256 bda949f555f730887b54d12627fdf17f290b245cf03ca14b7c4fc5b996c33884 t/lib/App/Info/Handler/Print.pm
@@ -47,7 +47,7 @@
 SHA256 7ea6b4ee4b5cd6b0b44939544138503ede324c8a85a06a8b51334d62c1298669 t/lib/App/Info/RDBMS/PostgreSQL.pm
 SHA256 36b5ac866344827a286687f036ed2702d2ccdee450ad1581a64995523b6df976 t/lib/App/Info/Request.pm
 SHA256 6725541fdeb205716695fca6ff90f77d4e37e33f7d2cefab0b8f946876f646f9 t/lib/App/Info/Util.pm
-SHA256 e37a46dd0a9b569e89de9549f3a00d90327b348f3fc67d28fb8a0508cbb2a498 testme.tmp.pl
-SHA256 f9567669852e55092c612e4f63a2e0540472947555fc8a57f429fa8383970c49 types.c
-SHA256 064c0dc289767d594b1272525c28219fc7304fe2aa815b9b29a043c90ec51c12 types.h
+SHA256 eedc5a43373937237f35a298f6945d87dc0144c91eaae3eea4a19e79d0ae462c testme.tmp.pl
+SHA256 6b5ec7d1edf69f91407a7d5efd75e4dcde8a583434301fa48fe1ff50ffb1129d types.c
+SHA256 789d430468f518ec7d46114bae5fcb11f08f29bd573999b02712ac8b6e75a72a types.h
 SHA256 4628f92764bdb3e2b04bda7f30fc497231fbbf80dfd24cc09ee3df2e6d6d4387 win32.mak
==> MISMATCHED content between SIGNATURE and distribution files! <==

**Comment by ilmari** [comment]
@turnstep ping?

**Comment by esabol** [comment]
Is this resolved by the 3.15.1 release?

**Comment by turnstep** [comment]
Yes, it seems to work for me but hopefully the OP can verify on their machine.

**Comment by turnstep** [comment]
Going to close this as I'm 99% sure this is fixed in 3.15.1
