### ISSUE TITLE
pg_getcopydata add an extra character at the end

### ISSUE THREAD

**Issue by cherio** [bucardo/dbdpg#89]
The following code 

```
my $row;
$dbh->do("COPY (SELECT 'abc') TO STDOUT");
$dbh->pg_getcopydata($row);
print("SURPRISE!\n") if $row =~ /\n$/s;
```

initializes $row with a 4-character string adding an extra `0x0A` (new line `'\n'`) on top of the value returned from the server.

I didn't find any mention of this behavior in the document. Maybe there is a way to configure that but it is not obvious from the module description.

`DBD::Pg` module version is 3.15.0 supplied from the standard Ubuntu 20.04 repository.
`Perl` version is 5.30 also coming with the standard Ubuntu 20.04 distribution.

**Comment by ilmari** [comment]
> initializes $row with a 4-character string adding an extra `0x0A` (new line `'\n'`) on top of the value returned from the server.

That is part of the PostgreSQL `COPY` format: each row is terminated by a newline, and DBD::Pg passes the data through unmodified one row at a time.

> I didn't find any mention of this behavior in the document. Maybe there is a way to configure that but it is not obvious from the module description.

The documentation could perhaps be more explicit about this, with examples indicating the exact returned data.

**Comment by turnstep** [comment]
Thanks - docs now mention a newline as of d6553253ae06f27272271ccab73f606de1c5663f
