### ISSUE TITLE
 Compilation failed in require at (eval 20) line 3 

### ISSUE THREAD

**Issue by joguess** [bucardo/dbdpg#93]
Hello 

I got the following error when I run a perl program : 

install_driver(Pg) failed: Attempt to reload DBD/Pg.pm aborted Compilation failed in require at (eval 20) line 3 at /usr/local/share/perl5/Ora2Pg.pm line 2173.

Regards.

J.

**Comment by turnstep** [comment]
It is hard to tell from this if the problem is with Ora2Pg or DBD::Pg. Are you sure DBD::Pg is installed? See if this outputs anything:

`perl -M5.01 -MDBD::Pg -e 'say $DBD::Pg::VERSION'
`

**Comment by turnstep** [comment]
Closing due to lack of response
